blueprint:
  name: "AmpliPi Announce"
  description: "Easy to use announcement builder"
  domain: automation
  author: Micro-Nova

  input:
    trigger_input:
      name: "Triggers"
      description: "What would you like to cause the automation to execute?"
      selector:
        trigger:

    message:
      name: "Message"
      description: "What would you like to announce?"
      default: "Any"
      selector:
        text:
          multiline: true

    cache:
      name: "Cache"
      description: "Would you like to save the tts to the disk? Good if you expect to use this announcement often, bad if this is a one-off or uncommon announcement."
      default: true
      selector:
        boolean:
        
mode: single

trigger: !input trigger_input

action:
  - service: tts.speak
    data:
      cache: !input cache
      media_player_entity_id: media_player.amplipi_announcement
      message: !input message
    target:
      entity_id: tts.google_translate_en_com
      