blueprint:
  name: "AmpliPi Start Streaming"
  description: "Connect a Source to a Stream and assign Zone(s) to the Source. After filling out these sections, hit the three dots in the top right and hit 'Take Control' to set the triggers of the automation"
  domain: automation

  input:
    source:
      name: "Source"
      description: "Select the source"
      selector:
        entity:
          filter:
            - device_class: receiver
            - integration: AmpliPi

    stream:
      name: "Stream"
      description: "Select the audio stream."
      selector:
        entity:
          filter:
            - device_class: "stream"
            - integration: AmpliPi

    zones:
      name: "Zones"
      description: "Select one or more zones for audio output."
      selector:
        entity:
          filter:
            - device_class: speaker
            - integration: AmpliPi
          multiple: true

mode: single

action:
  - service: media_player.select_source
    target:
      entity_id: !input source
    data:
      source: !input stream

  - delay: "00:00:01"

  - repeat:
      for_each: !input zones
      sequence:
        - service: media_player.select_source
          target:
            entity_id: "{{ repeat.item }}"
          data:
            source: !input source
