blueprint:
  name: "AmpliPi Start Streaming"
  description: "Connect a Source to a Stream and assign Zone(s) to the Source."
  domain: automation
  input:
    source:
      name: "Source"
      description: "Select the source"
      selector:
        entity:
          domain: media_player
          include_entities: "{{ states.media_player 
             | selectattr('attributes.friendly_name', 'contains', 'AmpliPi')
             | selectattr('attributes.friendly_name', 'contains', 'Source') 
             | map(attribute='entity_id') 
             | list | to_json }}"
          multiple: false
    stream:
      name: "Stream"
      description: "Select the audio stream."
      selector:
        select:
          options: "{{ state_attr('media_player.amplipi_source_1', 'source_list') | default([]) }}"
          multiple: false
    zones:
      name: "Zones"
      description: "Select one or more zones for audio output."
      selector:
        entity:
          domain: media_player
          include_entities: "{{ states.media_player 
             | selectattr('attributes.friendly_name', 'contains', 'AmpliPi')
             | selectattr('attributes.friendly_name', 'contains', 'Zone') 
             | map(attribute='entity_id') 
             | list | to_json
           + 
           states.media_player 
             | selectattr('attributes.friendly_name', 'contains', 'AmpliPi')
             | selectattr('attributes.friendly_name', 'contains', 'Group') 
             | map(attribute='entity_id') 
             | list | to_json }}
             "
          multiple: true

mode: single

trigger:
  - platform: state
    entity_id: !input source

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id in states('sensor.amplipi_sources').split(',') }}"
        sequence:
          - service: media_player.select_source
            target:
              entity_id: !input source
            data:
              source: !input stream

  - delay: "00:00:01"

  - repeat:
      for_each: !input zones
      sequence:
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ repeat.item in states('sensor.amplipi_zones').split(',') }}"
              sequence:
                - service: media_player.select_source
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    source: !input source
