blueprint:
  name: "AmpliPi Start Streaming"
  description: "Connect a Source to a Stream and assign Zone(s) to the Source."
  domain: automation
  input:
    source:
      name: "Source"
      description: "Select the source"
      selector:
        entity:
          domain: media_player
          multiple: false
          filter:
            - attributes:
                friendly_name: "/AmpliPi.*Source/"

    stream:
      name: "Stream"
      description: "Select the audio stream."
      selector:
        select:
          options: "{{ state_attr('media_player.amplipi_source_1', 'source_list') | default([]) }}"

    zones:
      name: "Zones"
      description: "Select one or more zones for audio output."
      selector:
        entity:
          domain: media_player
          multiple: true
          filter:
            - attributes:
                friendly_name: "/AmpliPi.*(Zone|Group)/"

mode: single

trigger:
  - platform: state
    entity_id: !input source

action:
  - service: media_player.select_source
    target:
      entity_id: !input source
    data:
      source: !input stream

  - delay: "00:00:01"

  - repeat:
      for_each: !input zones
      sequence:
        - service: media_player.select_source
          target:
            entity_id: "{{ repeat.item }}"
          data:
            source: !input source
